'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

interface WorkItem {
  id: string
  title: string
  category: string
  domain: string
  completedAt: string
  weekStart: string
  impact?: string | null
  autoGenerated?: boolean
}

interface Props {
  userId: string
  existingItems: WorkItem[]
  manualItems?: WorkItem[]
}

const CATEGORIES = ['advancement', 'maintenance', 'reactive', 'busywork']
const DOMAINS = ['career', 'fitness', 'finance', 'personal', 'learning']
const CATEGORY_COLORS: Record<string, string> = {
  advancement: '#9FE7C0',
  maintenance: '#9FCBFF',
  reactive: '#F3D58A',
  busywork: '#FFB4A8',
}

export default function WorkItemLogger({ userId, existingItems, manualItems }: Props) {
  const router = useRouter()
  const [title, setTitle] = useState('')
  const [category, setCategory] = useState('advancement')
  const [domain, setDomain] = useState('career')
  const [impact, setImpact] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [expandedCat, setExpandedCat] = useState<string | null>(null)

  const manualOnly = manualItems ?? existingItems.filter(w => !w.autoGenerated)
  const grouped = CATEGORIES.reduce((acc, cat) => {
    acc[cat] = manualOnly.filter(w => w.category === cat)
    return acc
  }, {} as Record<string, WorkItem[]>)
  const hasManual = manualOnly.length > 0

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!title.trim()) return
    setLoading(true)
    setError('')
    try {
      const res = await fetch('/api/anti-drift/items', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId, title, category, domain, impact: impact || null }),
      })
      if (!res.ok) throw new Error('Failed to save')
      setTitle('')
      setImpact('')
      router.refresh()
    } catch {
      setError('Failed to save item.')
    } finally {
      setLoading(false)
    }
  }

  async function handleDelete(id: string) {
    await fetch(`/api/anti-drift/items?id=${id}`, { method: 'DELETE' })
    router.refresh()
  }

  return (
    <div className="card">
      <div style={{ marginBottom: 14 }}>
        <h2 style={{ fontSize: 15, fontWeight: 700, color: '#F5F5F7', marginBottom: 4 }}>Work Items</h2>
        <p style={{ fontSize: 12, color: '#6E6E73' }}>
          Most items are auto-generated from your completed tasks and milestones. Use this to add supplementary context.
        </p>
      </div>

      {/* Collapsed manual add form */}
      <button
        onClick={() => setFormOpen(v => !v)}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          background: 'rgba(255,255,255,0.04)',
          border: '1px solid rgba(255,255,255,0.08)',
          borderRadius: 8,
          padding: '8px 14px',
          color: '#A1A1A6',
          fontSize: 12,
          fontWeight: 600,
          cursor: 'pointer',
          width: '100%',
          marginBottom: formOpen ? 12 : 0,
        }}
      >
        <span style={{ fontSize: 14 }}>{formOpen ? '−' : '+'}</span>
        Add Manual Item
        {!formOpen && (
          <span style={{ marginLeft: 'auto', fontSize: 10, color: '#6E6E73' }}>secondary / supplementary</span>
        )}
      </button>

      {formOpen && (
        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 20, padding: '12px', background: 'rgba(255,255,255,0.02)', borderRadius: 8, border: '1px solid rgba(255,255,255,0.06)' }}>
          <input
            placeholder="What did you complete?"
            value={title}
            onChange={e => setTitle(e.target.value)}
            style={{ background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 8, padding: '8px 12px', color: '#F5F5F7', fontSize: 13, width: '100%', boxSizing: 'border-box' }}
          />
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <select
              value={category}
              onChange={e => setCategory(e.target.value)}
              style={{ background: '#0d0d0e', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 8, padding: '8px 12px', color: '#F5F5F7', fontSize: 13 }}
            >
              {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
            <select
              value={domain}
              onChange={e => setDomain(e.target.value)}
              style={{ background: '#0d0d0e', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 8, padding: '8px 12px', color: '#F5F5F7', fontSize: 13 }}
            >
              {DOMAINS.map(d => <option key={d} value={d}>{d}</option>)}
            </select>
          </div>
          <input
            placeholder="Impact (optional): What changed permanently?"
            value={impact}
            onChange={e => setImpact(e.target.value)}
            style={{ background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 8, padding: '8px 12px', color: '#F5F5F7', fontSize: 13, width: '100%', boxSizing: 'border-box' }}
          />
          {error && <div style={{ fontSize: 12, color: '#FFB4A8' }}>{error}</div>}
          <button
            type="submit"
            disabled={loading || !title.trim()}
            style={{ background: 'rgba(201,184,255,0.15)', border: '1px solid rgba(201,184,255,0.3)', color: '#C9B8FF', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 600, cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.6 : 1 }}
          >
            {loading ? 'Saving...' : '+ Add Item'}
          </button>
        </form>
      )}

      {/* Manual items list (collapsed by default) */}
      {hasManual && (
        <div style={{ marginTop: formOpen ? 0 : 12 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#6E6E73', marginBottom: 10 }}>
            Manual Items ({manualOnly.length})
          </div>
          {CATEGORIES.map(cat => {
            const items = grouped[cat]
            if (items.length === 0) return null
            const isOpen = expandedCat === cat
            return (
              <div key={cat} style={{ marginBottom: 8 }}>
                <button
                  onClick={() => setExpandedCat(isOpen ? null : cat)}
                  style={{ background: 'none', border: 'none', padding: '6px 0', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8, width: '100%' }}
                >
                  <div style={{ width: 8, height: 8, borderRadius: 2, background: CATEGORY_COLORS[cat], flexShrink: 0 }} />
                  <span style={{ fontSize: 13, fontWeight: 600, color: CATEGORY_COLORS[cat] }}>{cat}</span>
                  <span style={{ fontSize: 11, color: '#A1A1A6' }}>({items.length})</span>
                  <span style={{ fontSize: 11, color: '#A1A1A6', marginLeft: 'auto' }}>{isOpen ? '▲' : '▼'}</span>
                </button>
                {isOpen && (
                  <div style={{ paddingLeft: 16 }}>
                    {items.slice(0, 8).map(item => (
                      <div
                        key={item.id}
                        style={{
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'flex-start',
                          padding: '6px 0',
                          borderBottom: '1px solid rgba(255,255,255,0.04)',
                        }}
                      >
                        <div style={{ flex: 1 }}>
                          <div style={{ fontSize: 13, color: '#F5F5F7' }}>{item.title}</div>
                          <div style={{ fontSize: 11, color: '#A1A1A6', marginTop: 2 }}>
                            {item.domain} · {new Date(item.completedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
                          </div>
                          {item.impact && <div style={{ fontSize: 11, color: '#9FE7C0', marginTop: 1 }}>→ {item.impact}</div>}
                        </div>
                        <button
                          onClick={() => handleDelete(item.id)}
                          style={{ background: 'none', border: 'none', color: '#FFB4A8', cursor: 'pointer', fontSize: 12, padding: '2px 6px', flexShrink: 0 }}
                        >
                          ✕
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}

      {!hasManual && !formOpen && (
        <div style={{ fontSize: 12, color: '#6E6E73', marginTop: 8, fontStyle: 'italic' }}>
          No manual items. Use the form above if you need to add context not captured automatically.
        </div>
      )}
    </div>
  )
}
