import { prisma } from '@/lib/db'
import { NextRequest, NextResponse } from 'next/server'
import { syncSourceCompletion } from '@/lib/execution-planner'

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params

  const task = await prisma.weeklyTask.findUnique({
    where: { id },
    include: { goal: true, weeklyPlan: { include: { quarter: { select: { status: true } } } } },
  })
  if (!task) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  if (task.weeklyPlan?.quarter?.status === 'closed') {
    return NextResponse.json({ error: 'Cannot update tasks in closed quarters' }, { status: 403 })
  }

  const completed = !task.completed
  const updated = await prisma.weeklyTask.update({
    where: { id },
    data: {
      completed,
      completedAt: completed ? new Date() : null,
      status: completed ? 'done' : 'planned',
    },
  })

  // ── Sync completion back to source entity ──────────────────────────────────
  await syncSourceCompletion(id, completed)

  // ── Auto-create WorkItem for anti-drift when completing (not uncompleting) ─
  if (completed) {
    const domain =
      task.domain ??
      (task.taskType === 'workout' || task.taskType === 'recovery' ? 'fitness'
      : task.taskType === 'study'   ? 'learning'
      : task.sourceModule === 'learning' ? 'learning'
      : task.sourceModule === 'fitness'  ? 'fitness'
      : task.sourceModule === 'career'   ? 'career'
      : task.goal?.category === 'career' ? 'career'
      : task.goal?.category === 'learning' ? 'learning'
      : task.goal?.category === 'finance'  ? 'finance'
      : 'personal')

    const category =
      task.goal?.strategicRole === 'career_capital' || task.goal?.strategicRole === 'high_upside_bet'
        ? 'advancement'
        : task.effort === 3 ? 'advancement'
        : 'maintenance'

    const now = new Date()
    const dayOfWeek = now.getDay()
    const monday = new Date(now)
    monday.setDate(now.getDate() - (dayOfWeek === 0 ? 6 : dayOfWeek - 1))
    monday.setHours(0, 0, 0, 0)

    const plan = task.weeklyPlan
    const quarter = plan
      ? await prisma.quarter.findUnique({ where: { id: plan.quarterId } })
      : null

    if (quarter) {
      // ── Idempotent: don't create duplicate WorkItem for this task ──────────
      const existingWorkItem = await prisma.workItem.findFirst({
        where: { sourceType: 'task', sourceId: task.id },
      })

      if (!existingWorkItem) {
        await prisma.workItem
          .create({
            data: {
              userId: quarter.userId,
              title: task.title,
              category,
              domain,
              completedAt: new Date(),
              weekStart: monday,
              autoGenerated: true,
              sourceType: 'task',
              sourceId: task.id,
            },
          })
          .catch(() => {})
      }

      // ── Fitness sync: create WorkoutLog when a workout task is completed ────
      if (task.taskType === 'workout' || (task.domain === 'fitness' && task.taskType !== 'recovery')) {
        const existingLog = await prisma.workoutLog.findFirst({
          where: { linkedWeeklyTaskId: task.id },
        })
        if (!existingLog) {
          await prisma.workoutLog
            .create({
              data: {
                userId:             quarter.userId,
                type:               task.title,
                date:               new Date(),
                linkedWeeklyTaskId: task.id,
              },
            })
            .catch(() => {})
        }
      }
    }
  }

  return NextResponse.json(updated)
}
