import { prisma } from '@/lib/db'
import { NextRequest, NextResponse } from 'next/server'

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params

  const task = await prisma.weeklyTask.findUnique({
    where: { id },
    include: {
      goal: true,
      weeklyPlan: true,
    },
  })
  if (!task) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const completed = !task.completed
  const updated = await prisma.weeklyTask.update({
    where: { id },
    data: { completed, completedAt: completed ? new Date() : null },
  })

  // Auto-create WorkItem for anti-drift when completing (not uncompleting)
  if (completed) {
    const domain =
      task.taskType === 'workout' || task.taskType === 'cardio' || task.taskType === 'sauna'
        ? 'fitness'
        : task.goal?.category === 'career'
        ? 'career'
        : task.goal?.category === 'learning'
        ? 'learning'
        : task.goal?.category === 'finance'
        ? 'finance'
        : 'personal'

    const category =
      task.goal?.strategicRole === 'career_capital' || task.goal?.strategicRole === 'high_upside_bet'
        ? 'advancement'
        : task.effort === 3
        ? 'advancement'
        : task.effort === 2
        ? 'maintenance'
        : 'maintenance'

    // Get weekStart (Monday of current week)
    const now = new Date()
    const dayOfWeek = now.getDay()
    const monday = new Date(now)
    monday.setDate(now.getDate() - (dayOfWeek === 0 ? 6 : dayOfWeek - 1))
    monday.setHours(0, 0, 0, 0)

    // Get userId from weeklyPlan → quarter
    const plan = task.weeklyPlan
    const quarter = plan
      ? await prisma.quarter.findUnique({ where: { id: plan.quarterId } })
      : null

    if (quarter) {
      await prisma.workItem
        .create({
          data: {
            userId: quarter.userId,
            title: task.title,
            category,
            domain,
            completedAt: new Date(),
            weekStart: monday,
            autoGenerated: true,
            sourceType: 'task',
            sourceId: task.id,
          },
        })
        .catch(() => {}) // Don't fail the toggle if this errors
    }
  }

  return NextResponse.json(updated)
}
