import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { createAnthropicClient } from '@/lib/anthropic'
import { getWeekBounds } from '@/lib/quarters'

const client = createAnthropicClient()

export async function POST(req: NextRequest) {
  const body = await req.json()
  const { userId, periodType } = body

  const now = new Date()
  let periodStart: Date
  if (periodType === 'quarterly') {
    periodStart = new Date(now)
    periodStart.setMonth(now.getMonth() - 3)
  } else {
    periodStart = new Date(now)
    periodStart.setMonth(now.getMonth() - 1)
  }
  const periodEnd = now

  const { monday } = getWeekBounds()

  // ── Sync auto work items from milestone completions ─────────────────────────
  const completedMilestones = await prisma.milestone.findMany({
    where: {
      completed: true,
      completedAt: { gte: periodStart, lte: periodEnd },
      goal: { userId },
    },
    include: { goal: true },
  })

  for (const m of completedMilestones) {
    const exists = await prisma.workItem.findFirst({
      where: { sourceType: 'milestone', sourceId: m.id },
    })
    if (!exists) {
      await prisma.workItem.create({
        data: {
          userId,
          title: `Milestone: ${m.title}`,
          category: 'advancement',
          domain: m.goal.category || 'career',
          completedAt: m.completedAt!,
          weekStart: monday,
          autoGenerated: true,
          sourceType: 'milestone',
          sourceId: m.id,
        },
      }).catch(() => {})
    }
  }

  // ── Fetch all work items for the period ─────────────────────────────────────
  // Auto-generated items first (primary), then manual (supplementary)
  const [autoWorkItems, manualWorkItems] = await Promise.all([
    prisma.workItem.findMany({
      where: { userId, completedAt: { gte: periodStart, lte: periodEnd }, autoGenerated: true },
    }),
    prisma.workItem.findMany({
      where: { userId, completedAt: { gte: periodStart, lte: periodEnd }, autoGenerated: false },
    }),
  ])

  const workItems = [...autoWorkItems, ...manualWorkItems]
  const total = workItems.length || 1

  const countOf = (cat: string) => workItems.filter(w => w.category === cat).length
  const pct = (cat: string) => Math.round((countOf(cat) / total) * 100)

  const advancementPct = pct('advancement')
  const maintenancePct = pct('maintenance')
  const reactivePct = pct('reactive')
  const busyworkPct = pct('busywork')

  const autoSummary = autoWorkItems
    .map(w => `[AUTO|${w.category}|${w.domain}] ${w.title}${w.impact ? ' → ' + w.impact : ''}`)
    .join('\n')
  const manualSummary = manualWorkItems
    .map(w => `[MANUAL|${w.category}|${w.domain}] ${w.title}${w.impact ? ' → ' + w.impact : ''}`)
    .join('\n')

  const itemSummary = [
    autoSummary ? `AUTO-TRACKED (${autoWorkItems.length} items):\n${autoSummary}` : '',
    manualSummary ? `MANUAL (${manualWorkItems.length} items):\n${manualSummary}` : '',
  ]
    .filter(Boolean)
    .join('\n\n')

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    system: `You are a strategic performance analyst. Analyze work distribution data and return ONLY valid JSON. No markdown, no explanation.`,
    messages: [
      {
        role: 'user',
        content: `Period: ${periodType} (${periodStart.toISOString().slice(0, 10)} to ${now.toISOString().slice(0, 10)})
Distribution: advancement=${advancementPct}%, maintenance=${maintenancePct}%, reactive=${reactivePct}%, busywork=${busyworkPct}%
Total items: ${workItems.length} (${autoWorkItems.length} auto-tracked, ${manualWorkItems.length} manual)
Work items:
${itemSummary || '(no items logged)'}

Return JSON with this exact structure:
{
  "momentum": "forward_strongly|forward_slowly|stagnant|fragmented|overloaded",
  "durableAssets": ["asset1", "asset2"],
  "insights": ["insight text"],
  "recommendations": ["action text"],
  "advancementPct": ${advancementPct},
  "maintenancePct": ${maintenancePct},
  "reactivePct": ${reactivePct},
  "busyworkPct": ${busyworkPct}
}`,
      },
    ],
  })

  const text = (response.content[0] as { type: string; text: string }).text
  const match = text.match(/\{[\s\S]*\}/)
  if (!match) return NextResponse.json({ error: 'AI parse error' }, { status: 500 })
  const parsed = JSON.parse(match[0])

  const report = await prisma.antiDriftReport.create({
    data: {
      userId,
      periodType,
      periodStart,
      periodEnd: now,
      advancementPct: parsed.advancementPct ?? advancementPct,
      maintenancePct: parsed.maintenancePct ?? maintenancePct,
      reactivePct: parsed.reactivePct ?? reactivePct,
      busyworkPct: parsed.busyworkPct ?? busyworkPct,
      momentum: parsed.momentum || 'stagnant',
      durableAssets: JSON.stringify(parsed.durableAssets || []),
      aiAnalysis: JSON.stringify(parsed),
    },
  })

  return NextResponse.json(report)
}
