import { prisma } from '@/lib/db'
import AntiDriftChart from '@/components/anti-drift/AntiDriftChart'
import WorkItemLogger from '@/components/anti-drift/WorkItemLogger'
import ReportGenerator from '@/components/anti-drift/ReportGenerator'
import AutoTrackedItems from '@/components/anti-drift/AutoTrackedItems'

export const dynamic = 'force-dynamic'

export default async function AntiDriftPage() {
  const user = await prisma.user.findFirst()
  if (!user) return <div style={{ color: '#FFB4A8', padding: 40 }}>No user found.</div>

  const thirtyDaysAgo = new Date()
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)

  const [autoItems, manualItems, antiDriftReports] = await Promise.all([
    prisma.workItem.findMany({
      where: { userId: user.id, completedAt: { gte: thirtyDaysAgo }, autoGenerated: true },
      orderBy: { completedAt: 'desc' },
    }),
    prisma.workItem.findMany({
      where: { userId: user.id, completedAt: { gte: thirtyDaysAgo }, autoGenerated: false },
      orderBy: { completedAt: 'desc' },
    }),
    prisma.antiDriftReport.findMany({
      where: { userId: user.id },
      orderBy: { createdAt: 'desc' },
      take: 3,
    }),
  ])

  const allItems = [...autoItems, ...manualItems]

  // Serialize
  const serializeItem = (w: typeof allItems[0]) => ({
    ...w,
    completedAt: w.completedAt.toISOString(),
    weekStart: w.weekStart.toISOString(),
  })

  const serializedAuto = autoItems.map(serializeItem)
  const serializedManual = manualItems.map(serializeItem)
  const serializedAll = allItems.map(serializeItem)

  return (
    <main style={{ maxWidth: 1100, margin: '0 auto', padding: '32px 20px' }}>
      <div style={{ marginBottom: 28 }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, color: '#F5F5F7' }}>Anti-Drift Report</h1>
        <p style={{ color: '#A1A1A6', fontSize: 14, marginTop: 4 }}>
          Movement vs advancement. Effort vs leverage. Data sourced from completed tasks and milestones.
        </p>
      </div>

      {allItems.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '48px 24px', marginBottom: 20 }}>
          <div style={{ fontSize: 36, marginBottom: 12 }}>📊</div>
          <div style={{ fontSize: 16, fontWeight: 700, color: '#F5F5F7', marginBottom: 8 }}>No work items yet</div>
          <p style={{ color: '#6E6E73', fontSize: 14, maxWidth: 400, margin: '0 auto' }}>
            Complete goals and milestones in your quarterly plan, or log work items manually below to start tracking your effort breakdown.
          </p>
        </div>
      ) : (
        <>
          <AntiDriftChart workItems={serializedAll} />
          <AutoTrackedItems items={serializedAuto.map(i => ({ id: i.id, title: i.title, category: i.category, completedAt: i.completedAt }))} />
        </>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 20 }}>
        <WorkItemLogger
          userId={user.id}
          existingItems={serializedAll}
          manualItems={serializedManual}
        />
        <ReportGenerator
          userId={user.id}
          pastReports={antiDriftReports.map(r => ({
            ...r,
            periodStart: r.periodStart.toISOString(),
            periodEnd: r.periodEnd.toISOString(),
            createdAt: r.createdAt.toISOString(),
          }))}
        />
      </div>
    </main>
  )
}
